### ISSUE TITLE
request for updating the URL of the model

### ISSUE THREAD

**Issue by BobHuangC** [zhisheng01/SLU-project-CS4314#3]
Hello, I'm writing to kindly request an update for the download URL for your model.
It seems that the original download link https://jbox.sjtu.edu.cn/l/w1Nzt6 has expired. Would it be possible for you to provide an updated link?
Many thanks!

**Comment by zszheng147** [comment]
Hi,

Thanks for your interest. I'm sorry to inform you that we have deleted those checkpoints from everywhere since it's just a course project.
I think it's ok to just rerun our code and get your own checkpoint, and the result would be similar or the same.

**Comment by BobHuangC** [comment]
Got it! Many thanks again for your wonderful work and prompt response!
